name: Feature request
description: Propose an improvement to spill
title: 'feat: '
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
    validations:
      required: true
  - type: textarea
    id: impact
    attributes:
      label: User impact
      description: Who benefits, and how will we know?
